#!/bin/bash
# SQLite Quick Reference for Employee Management System

echo "=== SQLite Command-Line Reference ==="
echo ""
echo "Database file: employee_management.db"
echo ""
echo "1. OPEN DATABASE INTERACTIVE MODE:"
echo "   sqlite3 employee_management.db"
echo ""
echo "2. QUICK QUERIES (without entering interactive mode):"
echo "   sqlite3 employee_management.db 'SELECT * FROM Admin;'"
echo "   sqlite3 employee_management.db 'SELECT * FROM Employee;'"
echo ""
echo "3. VIEW DATABASE STRUCTURE:"
echo "   sqlite3 employee_management.db '.tables'"
echo "   sqlite3 employee_management.db '.schema Admin'"
echo "   sqlite3 employee_management.db '.schema Employee'"
echo ""
echo "4. EMPLOYEE OPERATIONS:"
echo "   # Add employee"
echo "   sqlite3 employee_management.db \"INSERT INTO Employee (name, email, department, salary) VALUES ('Jane Smith', 'jane@example.com', 'HR', 55000);\""
echo ""
echo "   # View all employees"
echo "   sqlite3 employee_management.db 'SELECT * FROM Employee;'"
echo ""
echo "   # Update employee salary"
echo "   sqlite3 employee_management.db \"UPDATE Employee SET salary = 60000 WHERE emp_id = 1;\""
echo ""
echo "   # Delete employee"
echo "   sqlite3 employee_management.db 'DELETE FROM Employee WHERE emp_id = 1;'"
echo ""
echo "5. FORMATTED OUTPUT:"
echo "   sqlite3 -header -column employee_management.db 'SELECT * FROM Employee;'"
echo ""
echo "6. EXPORT DATABASE:"
echo "   sqlite3 employee_management.db .dump > backup.sql"
echo ""
echo "7. INTERACTIVE MODE COMMANDS:"
echo "   .tables          - List all tables"
echo "   .schema          - Show all table schemas"
echo "   .headers on      - Show column headers"
echo "   .mode column     - Display in columns"
echo "   .quit or .exit   - Exit interactive mode"
echo ""
echo "=== Java Compilation & Execution ==="
echo ""
echo "COMPILE:"
echo "  javac -cp '.:sqlite-jdbc-3.45.1.0.jar:javax.servlet-api-4.0.1.jar' src/*.java"
echo ""
echo "TEST DATABASE:"
echo "  java -cp '.:src:sqlite-jdbc-3.45.1.0.jar:slf4j-api-2.0.9.jar:slf4j-simple-2.0.9.jar' TestDatabase"
echo ""
echo "=== Required JAR Files ==="
echo "  ✓ sqlite-jdbc-3.45.1.0.jar        - SQLite JDBC driver"
echo "  ✓ slf4j-api-2.0.9.jar             - Logging API"
echo "  ✓ slf4j-simple-2.0.9.jar          - Logging implementation"
echo "  ✓ javax.servlet-api-4.0.1.jar     - Servlet API (for servlets)"
